-- Пользователи
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    login VARCHAR(255) NOT NULL UNIQUE,
    user_name VARCHAR(255),
    birthday DATE
    );

-- Статусы дружбы
CREATE TABLE IF NOT EXISTS friendship_status (
status_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
status_name VARCHAR(20) NOT NULL UNIQUE
    );

-- Рейтинги MPA
CREATE TABLE IF NOT EXISTS mpa_ratings (
    rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_name VARCHAR(10) NOT NULL UNIQUE
    );

-- Жанры
CREATE TABLE IF NOT EXISTS genres (
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name VARCHAR(50) NOT NULL UNIQUE
    );

-- Фильмы
CREATE TABLE IF NOT EXISTS films (
    film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name VARCHAR(255) NOT NULL,
    description VARCHAR(200) NOT NULL,
    release_date DATE NOT NULL,
    duration INTEGER NOT NULL CHECK (duration > 0),
    mpa_rating_id INTEGER NOT NULL,
    FOREIGN KEY (mpa_rating_id) REFERENCES mpa_ratings(rating_id),
    CONSTRAINT check_release_date CHECK (release_date >= '1895-12-28')
    );

-- Дружбы
CREATE TABLE IF NOT EXISTS friendships (
user_id BIGINT NOT NULL,
friend_id BIGINT NOT NULL,
status_id INTEGER NOT NULL,
PRIMARY KEY (user_id, friend_id),
FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
FOREIGN KEY (friend_id) REFERENCES users(user_id) ON DELETE CASCADE,
FOREIGN KEY (status_id) REFERENCES friendship_status(status_id),
CONSTRAINT check_not_self_friend CHECK (user_id != friend_id)
);

-- Связь фильм-жанр
CREATE TABLE IF NOT EXISTS film_genres (
film_id BIGINT NOT NULL,
genre_id INTEGER NOT NULL,
PRIMARY KEY (film_id, genre_id),
FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE,
FOREIGN KEY (genre_id) REFERENCES genres(genre_id) ON DELETE CASCADE
);

-- Лайки
CREATE TABLE IF NOT EXISTS likes (
film_id BIGINT NOT NULL,
user_id BIGINT NOT NULL,
PRIMARY KEY (film_id, user_id),
FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE,
FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);